version: '3.7'
services:
  node:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    # depends_on:
    #   - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm run start:n
    restart: on-failure
    networks:
      - app-network

  postgres:
    build: ./db
    env_file:
      - .env
    ports:
     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    volumes:     
     - dbdata:/usr/app/db
    networks:
     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: 